# Generated by Django 6.0.6 on 2026-07-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_candidateprofile_bio_candidateprofile_cover_letter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='bio',
            new_name='about',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='education',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
