# Generated by Django 6.0.6 on 2026-07-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_bio_candidateprofile_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
